### ISSUE TITLE
[Feature] SideKey

### ISSUE THREAD

**Issue by roeNapanget** [ananjaser1211/FloydT_Reports#12]
Power off button in quick panel should have the side key option like in Nobel rom
Next the settings should have search option like looking for apps.
That's all.

**Comment by ananjaser1211** [comment]
Will be working on adding sidekey in the next build hopefully.

the search option can be enabled by selecting settings Tips in aroma.

"Settings Tips  - Search and Tips in Settings App"

**Comment by roeNapanget** [comment]
Wow thanks for this reply I do appreciate it. But I do have some
concerns,iwant to use magisk istead of kernel su,Im comportable with magisk
so please do help me how can I install magisk with this os.. anyways thanks
man..

**Comment by ananjaser1211** [comment]
Download this patch and flash it https://github.com/ananjaser1211/FloydT_Reports/issues/9#issuecomment-1740821663

then flash magisk zip from twrp. the next release will include the patch by default.
