### ISSUE TITLE
[BUG] Face unlock does not works

### ISSUE THREAD

**Issue by ghost** [ananjaser1211/FloydT_Reports#13]
Face unlock does not work
Device : starlte

**Comment by duhansysl** [comment]
@Yigitqweqew those people has problems on their eyes

**Comment by duhansysl** [comment]
@Yigitqweqew it is not working already. it is a bug on Android 13. still needs to be fixed. so don't complain. go and read the thread much better next time. cheers

**Comment by ghost** [comment]
@duhansysl Thank you

**Comment by duhansysl** [comment]
@Yigitqweqew you are welcome. hopefully we will fix it in future.

**Comment by ananjaser1211** [comment]
Duplicate #2
