### ISSUE TITLE
[BUG] FOOD mode and Portrait are not working on G960F/N [PATCH]

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydT_Reports#16]
**Description of the Bug**
FOOD mode FCs when opened
Portrait Mode FCs when opened

**Expected Behaviour**
Portrait is expected not to work, see #6 
Food mode SHOULD be working

**Smartphone**
- G960F/N
- S9 Non PLUS only

**Additional Information**
- Patch attached will disable broken rear portrait mode, and fix FOOD mode
- This is ONLY for the S9 NON PLUS

[FloydT_G960_DisablePortraitAndFixFoodMode.zip](https://github.com/ananjaser1211/FloydT_Reports/files/13799307/FloydT_G960_DisablePortraitAndFixFoodMode.zip)

**Comment by ananjaser1211** [comment]
Fixed with build 20 https://xdaforums.com/t/rom-oneui-5-1-galaxy-s9-s9-note9-intl-kor-g960x-g965x-n960x-floydrom-build-20-0-03-27-2024.4625579/post-89423784

**Comment by AkuKapten** [comment]
Patch work on n960f also?

**Comment by duhansysl** [comment]
@AkuKapten portrait mode works on galaxy note9 and s9+ which has tele lens. but s9
