### ISSUE TITLE
samsung pass[Feature]

### ISSUE THREAD

**Issue by ariwaw92** [ananjaser1211/FloydT_Reports#21]
**Description of the Feature**
<please make samsung pass working on this custom ROM, so far it's not working>

**Possible Visualization**

**Expected Behaviour**

**Smartphone**

 - Device:
 - Model:

**Origin of the Feature**

**Comment by PeterKnecht93** [comment]
Hello,
Samsung Pay and Pass can't be fixed on custom ROMs. For more information, see:
https://github.com/Mesa-Labs-Archive/KnoxPatch/issues/43
