### ISSUE TITLE
[BUG]Phone freezes after uninstalling an app

### ISSUE THREAD

**Issue by kamseunaam** [ananjaser1211/FloydT_Reports#23]
**Description of the Bug**
On the galaxy s9+, Uninstalling an app most times causes some other apps to freeze and then eventually the entire ui freezes and I can't even turn off the phone.
Sorry for my english
**How To Reproduce**
<!--Uninstall an app

**Smartphone**
Please complete the following information:
 - Device: [Galaxy S9+]
 - Model: [G965F]

**Comment by AkuKapten** [comment]
Same on the galaxy note 9, when uninstalling an app it will say uninstalling the app on the notif panel for 5 minutes and then 5 the phone will freezes and reboot itself. I will try to see if this becuase i dirty flash from build 19 or is this an bug on build 20

**Comment by hienp8** [comment]
I have same issue! Clean flash don't fix this. So normally I unistall app from Setting. It'll not frezze and restart phone

**Comment by AkuKapten** [comment]
> I have same issue! Clean flash don't fix this. So normally I unistall app from Setting. It'll not frezze and restart phone

What do you have, i have not ecountered this bug anymore after clean flashing it. Might have to use this rom further to know if the bug will happen again

**Comment by hienp8** [comment]
Here are the log error
[log_e.log](https://github.com/user-attachments/files/15741220/log_e.log)

**Comment by hienp8** [comment]
This is log file
[log.zip](https://github.com/user-attachments/files/15741749/log.zip)

**Comment by ananjaser1211** [comment]
Please re-test with Build 21 ([XDA](https://xdaforums.com/t/rom-oneui-5-1-galaxy-s9-s9-note9-intl-kor-g960x-g965x-n960x-floydrom-build-21-0-09-01-2024.4625579/post-89690846)) and re-open if the issue persists.
