### ISSUE TITLE
[BUG] Built-in spoofing interfering with Tricky Store functionality

### ISSUE THREAD

**Issue by Glennza1962** [ananjaser1211/FloydT_Reports#27]
Built-in spoofing interfering with Tricky Store functionality

"Just as a heads-up, if you use a custom ROM which integrates Play Integrity spoofing, e.g. crDroid, you will never pass STRONG."

](https://xdaforums.com/t/tricky-store-the-next-generation-pif.4683446/post-89647320)

Not sure that built-in spoofing is useful any more, might be better to remove it altogether?

S9 (SM-G960F)

**Comment by ananjaser1211** [comment]
Play integrity spoofing can now be disabled as of build 21 (https://xdaforums.com/t/rom-oneui-5-1-galaxy-s9-s9-note9-intl-kor-g960x-g965x-n960x-floydrom-build-21-0-09-01-2024.4625579/post-89690846)
