### ISSUE TITLE
[BUG] Magisk 26+ does not work

### ISSUE THREAD

**Issue by ananjaser1211** [ananjaser1211/FloydT_Reports#9]
**Describe the bug**
Requires Additional Setup, but never completes

**Smartphone (please complete the following information):**
 - Device: All devices

**Additional context**
- This is possibly due to the way we use CACHE partition for bloatware on the ROM
- Pre 26 Works, i.e 25.3 / Delta 25.3

**Comment by ananjaser1211** [comment]
This bug will be fixed in next release, the issue was due to lack of proper /CACHE partition as we use it for bloat, and the fallback cache partition was not setup properly

**Comment by Darkos999** [comment]
ok it works perfectly

**Comment by ananjaser1211** [comment]
Addressed with build 19
